# Generated by Django 5.1.7 on 2026-04-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Solicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("rectificacion", "Rectificacion de Calificacion"),
                            ("justificacion", "Justificacion de Inasistencia"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobada", "Aprobada"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="pendiente",
                        max_length=15,
                    ),
                ),
                ("descripcion", models.TextField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_resolucion", models.DateTimeField(blank=True, null=True)),
                ("respuesta", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Solicitud",
                "verbose_name_plural": "Solicitudes",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
