# Generated by Django 5.1.7 on 2026-04-06 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("solicitudes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitud",
            name="estudiante",
            field=models.ForeignKey(
                limit_choices_to={"rol": "estudiante"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solicitudes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="solicitud",
            name="resuelto_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solicitudes_resueltas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
