# Generated by Django 5.1.7 on 2026-05-17 20:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_alter_asistencia_estado'),
        ('calificaciones', '0007_alter_evaluacion_tipo'),
        ('solicitudes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='archivo_adjunto',
            field=models.FileField(blank=True, help_text='PDF o imagen (JPG/PNG). Máximo 5 MB.', null=True, upload_to='solicitudes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='asistencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_justificacion', to='asistencia.asistencia'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='calificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_recalificacion', to='calificaciones.calificacion'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='numero_solicitud',
            field=models.PositiveIntegerField(default=1, help_text='Número de solicitud para la misma evaluación/asistencia.'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='requiere_secretaria',
            field=models.BooleanField(default=False, help_text='True si es la segunda solicitud o más para la misma evaluación.'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='descripcion',
            field=models.TextField(help_text='Motivo detallado de la solicitud.'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=15),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('rectificacion', 'Rectificación de Calificación'), ('justificacion', 'Justificación de Inasistencia')], max_length=20),
        ),
    ]
