# Generated by Django 5.1.7 on 2026-05-17 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solicitudes", "0003_solicitud_archivo_adjunto_solicitud_asistencia_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistorialSolicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "estado_anterior",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_revision", "En Revisión"),
                            ("aprobada", "Aprobada"),
                            ("rechazada", "Rechazada"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "estado_nuevo",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_revision", "En Revisión"),
                            ("aprobada", "Aprobada"),
                            ("rechazada", "Rechazada"),
                        ],
                        max_length=15,
                    ),
                ),
                ("comentario", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "cambiado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="solicitudes.solicitud",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Solicitud",
                "verbose_name_plural": "Historial de Solicitudes",
                "ordering": ["-timestamp"],
            },
        ),
    ]
