# Generated by Django 5.1.7 on 2026-05-24 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solicitudes", "0005_archivosolicitud_certificadojustificacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivosolicitud",
            name="archivo",
            field=models.FileField(
                upload_to="solicitudes/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
    ]
