# Generated by Django 5.1.7 on 2026-05-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solicitudes", "0006_alter_archivosolicitud_archivo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionJustificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "deadline_dias",
                    models.PositiveIntegerField(
                        default=5, help_text="Días hábiles para resolver una justificación."
                    ),
                ),
                (
                    "alerta_dias",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Días antes del deadline para mostrar alerta amarilla.",
                    ),
                ),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración de Justificaciones",
                "verbose_name_plural": "Configuración de Justificaciones",
            },
        ),
    ]
