# Generated by Django 5.1.7 on 2026-04-06 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asignatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("descripcion", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Asignatura",
                "verbose_name_plural": "Asignaturas",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Periodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("activo", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Periodo Academico",
                "verbose_name_plural": "Periodos Academicos",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Paralelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(max_length=10)),
                ("horario", models.TextField(blank=True)),
                (
                    "asignatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paralelos",
                        to="academico.asignatura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paralelo",
                "verbose_name_plural": "Paralelos",
            },
        ),
    ]
