# Generated by Django 5.1.7 on 2026-04-06 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academico", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="paralelo",
            name="docente",
            field=models.ForeignKey(
                limit_choices_to={"rol": "docente"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paralelos_asignados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paralelo",
            name="estudiantes",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"rol": "estudiante"},
                related_name="paralelos_matriculados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paralelo",
            name="periodo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paralelos",
                to="academico.periodo",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paralelo",
            unique_together={("asignatura", "periodo", "nombre")},
        ),
    ]
