# Generated by Django 5.1.7 on 2026-04-07 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academico", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoLicencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("codigo", models.CharField(max_length=5, unique=True)),
                ("duracion_meses", models.PositiveIntegerField()),
                ("num_asignaturas", models.PositiveIntegerField()),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tipo de Licencia",
                "verbose_name_plural": "Tipos de Licencia",
            },
        ),
        migrations.AddField(
            model_name="asignatura",
            name="horas_lectivas",
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name="paralelo",
            name="capacidad_maxima",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="periodo",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="periodos_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="periodo",
            name="modificado_en",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name="paralelo",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="asignatura",
            name="tipos_licencia",
            field=models.ManyToManyField(
                blank=True, related_name="asignaturas", to="academico.tipolicencia"
            ),
        ),
        migrations.AddField(
            model_name="paralelo",
            name="tipo_licencia",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paralelos",
                to="academico.tipolicencia",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="paralelo",
            unique_together={("periodo", "tipo_licencia", "asignatura", "nombre")},
        ),
    ]
