# Generated by Django 5.1.7 on 2026-04-07 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academico", "0007_seed_tipolicencia"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paralelo",
            options={
                "ordering": ["periodo", "asignatura__codigo", "nombre"],
                "verbose_name": "Paralelo",
                "verbose_name_plural": "Paralelos",
            },
        ),
        migrations.AlterModelOptions(
            name="tipolicencia",
            options={
                "ordering": ["codigo"],
                "verbose_name": "Tipo de Licencia",
                "verbose_name_plural": "Tipos de Licencia",
            },
        ),
    ]
