# Generated by Django 5.1.7 on 2026-07-06 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academico", "0015_paralelo_docente_set_null"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CierrePeriodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("fin_periodo", "Fin de período"),
                            ("desactivacion", "Desactivación"),
                        ],
                        max_length=15,
                    ),
                ),
                ("fecha_corte", models.DateField()),
                ("generado_en", models.DateTimeField(auto_now_add=True)),
                ("datos", models.JSONField()),
                (
                    "generado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cierres_generados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "periodo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cierre",
                        to="academico.periodo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cierre de Período",
                "verbose_name_plural": "Cierres de Período",
                "ordering": ["-generado_en"],
            },
        ),
    ]
