# Generated by Django 5.1.7 on 2026-06-05 18:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversacionCopilot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=200)),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                ("ultima_actividad", models.DateTimeField(auto_now=True)),
                ("activa", models.BooleanField(default=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversaciones_copilot",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversación Copilot",
                "verbose_name_plural": "Conversaciones Copilot",
                "ordering": ["-ultima_actividad"],
            },
        ),
        migrations.CreateModel(
            name="MensajeCopilot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("user", "Usuario"),
                            ("assistant", "Asistente"),
                            ("system", "Sistema"),
                        ],
                        max_length=10,
                    ),
                ),
                ("contenido", models.TextField()),
                ("tokens_usados", models.PositiveIntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "conversacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes",
                        to="copilot.conversacioncopilot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje Copilot",
                "verbose_name_plural": "Mensajes Copilot",
                "ordering": ["timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="conversacioncopilot",
            index=models.Index(
                fields=["usuario", "-ultima_actividad"], name="copilot_con_usuario_367ead_idx"
            ),
        ),
    ]
