# Generated by Django 5.1.7 on 2026-04-07 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="bloqueado_hasta",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="direccion",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="usuario",
            name="intentos_fallidos",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="OTPToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("codigo", models.CharField(max_length=6)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("expira_en", models.DateTimeField()),
                ("usado", models.BooleanField(default=False)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Token OTP",
                "verbose_name_plural": "Tokens OTP",
                "indexes": [
                    models.Index(
                        fields=["usuario", "usado", "expira_en"],
                        name="usuarios_ot_usuario_55aa93_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RegistroAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("accion", models.CharField(max_length=50)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("detalle", models.TextField(blank=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_auditoria",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Auditoría",
                "verbose_name_plural": "Registros de Auditoría",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "accion", "timestamp"],
                        name="usuarios_re_usuario_f75752_idx",
                    )
                ],
            },
        ),
    ]
