# Generated by Django 5.1.7 on 2026-04-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_add_debe_cambiar_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("estudiante", "Estudiante"),
                    ("docente", "Docente"),
                    ("inspector", "Inspector"),
                    ("secretaria", "Secretaría"),
                ],
                max_length=20,
            ),
        ),
    ]
