# Generated by Django 5.1.7 on 2026-06-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0006_cedula_not_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("estudiante", "Estudiante"),
                    ("docente", "Docente"),
                    ("inspector", "Inspector"),
                    ("secretaria", "Secretaría"),
                    ("director_academico", "Director Académico"),
                ],
                max_length=20,
            ),
        ),
    ]
