# Generated by Django 5.1.7 on 2026-06-19 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academico", "0015_paralelo_docente_set_null"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReporteANT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("numero_resolucion", models.CharField(default="005-DIR-2022-ANT", max_length=50)),
                ("fecha_generacion", models.DateTimeField(auto_now_add=True)),
                ("total_estudiantes", models.PositiveIntegerField(default=0)),
                ("total_aprobados", models.PositiveIntegerField(default=0)),
                ("total_reprobados", models.PositiveIntegerField(default=0)),
                ("total_desertores", models.PositiveIntegerField(default=0)),
                ("total_en_curso", models.PositiveIntegerField(default=0)),
                ("archivo_pdf", models.FileField(upload_to="reportes/ant/%Y/%m/")),
                (
                    "archivo_excel",
                    models.FileField(blank=True, null=True, upload_to="reportes/ant/%Y/%m/"),
                ),
                ("hash_sha256", models.CharField(max_length=64)),
                (
                    "firma_responsable_imagen",
                    models.CharField(
                        blank=True,
                        help_text="Path relativo a la imagen de firma del responsable (PNG).",
                        max_length=300,
                    ),
                ),
                ("nombre_firmante", models.CharField(max_length=200)),
                ("cedula_firmante", models.CharField(max_length=20)),
                (
                    "cargo_firmante",
                    models.CharField(default="Director Académico ECPPP", max_length=100),
                ),
                ("notas", models.TextField(blank=True)),
                (
                    "generado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reportes_ant_generados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reportes_ant",
                        to="academico.periodo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte ANT",
                "verbose_name_plural": "Reportes ANT",
                "ordering": ["-fecha_generacion"],
                "indexes": [
                    models.Index(
                        fields=["periodo", "-fecha_generacion"],
                        name="reportes_re_periodo_4976c1_idx",
                    )
                ],
            },
        ),
    ]
