# Generated by Django 5.1.7 on 2026-04-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Calificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nota", models.DecimalField(decimal_places=2, max_digits=5)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("observaciones", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Calificacion",
                "verbose_name_plural": "Calificaciones",
            },
        ),
        migrations.CreateModel(
            name="Evaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("parcial1", "Parcial 1"),
                            ("parcial2_10h", "Parcial 2 (10h)"),
                            ("parcial3", "Parcial 3"),
                            ("parcial4_10h", "Parcial 4 (10h)"),
                            ("proyecto", "Proyecto"),
                            ("examen_final", "Examen Final"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "peso",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Peso porcentual de la evaluacion",
                        max_digits=5,
                    ),
                ),
                ("fecha", models.DateField(blank=True, null=True)),
                ("descripcion", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Evaluacion",
                "verbose_name_plural": "Evaluaciones",
            },
        ),
    ]
