# Generated by Django 5.1.7 on 2026-04-06 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academico", "0002_initial"),
        ("calificaciones", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="calificacion",
            name="estudiante",
            field=models.ForeignKey(
                limit_choices_to={"rol": "estudiante"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calificaciones",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="evaluacion",
            name="paralelo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluaciones",
                to="academico.paralelo",
            ),
        ),
        migrations.AddField(
            model_name="calificacion",
            name="evaluacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calificaciones",
                to="calificaciones.evaluacion",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="evaluacion",
            unique_together={("paralelo", "tipo")},
        ),
        migrations.AlterUniqueTogether(
            name="calificacion",
            unique_together={("evaluacion", "estudiante")},
        ),
    ]
