# Generated by Django 5.1.7 on 2026-05-11 22:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calificaciones", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calificacion",
            name="nota",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20),
                ],
            ),
        ),
    ]
