# Generated by Django 5.1.7 on 2026-05-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calificaciones", "0003_add_nota_validators"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluacion",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("parcial1", "Parcial 1"),
                    ("parcial2_10h", "Parcial 2 (10h)"),
                    ("parcial3", "Parcial 3"),
                    ("parcial4_10h", "Parcial 4 (10h)"),
                    ("examen_final", "Examen Final"),
                ],
                max_length=20,
            ),
        ),
    ]
