# Generated by Django 5.1.7 on 2026-05-14 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calificaciones", "0004_remove_proyecto_tipo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogCalificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("evaluacion_info", models.CharField(max_length=200)),
                ("estudiante_info", models.CharField(max_length=200)),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("creacion", "Creación"),
                            ("modificacion", "Modificación"),
                            ("recalificacion", "Recalificación"),
                            ("eliminacion", "Eliminación"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "valor_anterior",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "valor_nuevo",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("motivo", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "calificacion",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="calificaciones.calificacion",
                    ),
                ),
                (
                    "realizado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_calificacion",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Calificacion",
                "verbose_name_plural": "Logs de Calificaciones",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["calificacion", "timestamp"], name="calificacio_calific_7c9ddf_idx"
                    ),
                    models.Index(
                        fields=["realizado_por", "timestamp"],
                        name="calificacio_realiza_3f24c3_idx",
                    ),
                ],
            },
        ),
    ]
