# Generated by Django 5.1.7 on 2026-05-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0007_alter_evaluacion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logcalificacion',
            name='accion',
            field=models.CharField(choices=[('creacion', 'Creación'), ('modificacion', 'Modificación'), ('recalificacion', 'Recalificación'), ('eliminacion', 'Eliminación'), ('envio_planilla', 'Envío de Planilla'), ('aprobacion_planilla', 'Aprobación de Planilla'), ('rechazo_planilla', 'Rechazo de Planilla'), ('justificacion', 'Justificación de Asistencia')], max_length=25),
        ),
        migrations.AlterField(
            model_name='logcalificacion',
            name='estudiante_info',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logcalificacion',
            name='evaluacion_info',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
