# Generated by Django 5.1.7 on 2026-07-08 22:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academico", "0015_paralelo_docente_set_null"),
        ("calificaciones", "0008_log_tipos_macro_y_campos_opcionales"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionSubNotas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "evaluacion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracion_sub_notas",
                        to="calificaciones.evaluacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuracion de Sub-Notas",
                "verbose_name_plural": "Configuraciones de Sub-Notas",
            },
        ),
        migrations.CreateModel(
            name="SubNotaConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre de la sub-nota (ej. 'Tarea 1', 'Exposición')",
                        max_length=100,
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField()),
                (
                    "configuracion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="calificaciones.configuracionsubnotas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Configuracion de Sub-Notas",
                "verbose_name_plural": "Items de Configuracion de Sub-Notas",
                "ordering": ["orden"],
                "unique_together": {("configuracion", "orden")},
            },
        ),
        migrations.CreateModel(
            name="SubNotaParcial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre de la sub-nota (ej. 'Tarea 1', 'Exposición')",
                        max_length=100,
                    ),
                ),
                (
                    "nota",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("20")),
                        ],
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField()),
                (
                    "nota_final_parcial_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Si difiere del promedio, override manual del docente",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "justificacion_override",
                    models.TextField(
                        blank=True,
                        help_text=(
                            "Obligatoria si nota_final_parcial_override "
                            "difiere del promedio"
                        ),
                    ),
                ),
                (
                    "evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_notas",
                        to="calificaciones.evaluacion",
                    ),
                ),
                (
                    "matricula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_notas",
                        to="academico.matricula",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub-Nota de Parcial",
                "verbose_name_plural": "Sub-Notas de Parciales",
                "ordering": ["evaluacion", "orden"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("nota__gte", 0), ("nota__lte", 20)),
                        name="sub_nota_rango_0_20",
                    )
                ],
                "unique_together": {("evaluacion", "matricula", "orden")},
            },
        ),
    ]
