# Generated by Django 5.1.7 on 2026-07-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calificaciones", "0009_configuracionsubnotas_subnotaconfig_subnotaparcial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subnotaconfig",
            name="peso",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Peso porcentual de la sub-nota; los pesos deben sumar 100",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subnotaparcial",
            name="peso",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Peso porcentual de la sub-nota al momento del registro",
                max_digits=5,
                null=True,
            ),
        ),
    ]
