# Generated by Django 5.1.7 on 2026-07-14 16:02

from django.db import migrations, models


def _proyecto_a_parcial5(apps, schema_editor):
    Evaluacion = apps.get_model("calificaciones", "Evaluacion")
    Evaluacion.objects.filter(tipo="proyecto").update(tipo="parcial5")


def _parcial5_a_proyecto(apps, schema_editor):
    Evaluacion = apps.get_model("calificaciones", "Evaluacion")
    Evaluacion.objects.filter(tipo="parcial5").update(tipo="proyecto")


class Migration(migrations.Migration):

    dependencies = [
        ("calificaciones", "0010_subnotaconfig_peso_subnotaparcial_peso"),
    ]

    operations = [
        migrations.RunPython(_proyecto_a_parcial5, _parcial5_a_proyecto),
        migrations.AlterField(
            model_name="evaluacion",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("parcial1", "Parcial 1"),
                    ("parcial2_10h", "Parcial 2"),
                    ("parcial3", "Parcial 3"),
                    ("parcial4_10h", "Parcial 4"),
                    ("parcial5", "Parcial 5"),
                    ("examen_final", "Examen Final"),
                ],
                max_length=20,
            ),
        ),
    ]
